spring:
    datasource:
        url: jdbc:mysql://localhost:3308/eva_hospital_db?createDatabaseIfNotExist=true
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            format_sql: true